# NumPy

## ALWAYS import numpy as np
This is a convention that everyone follows. If you do not do this, other people will have a hard time reading your code

In [1]:
import numpy as np

## Numpy arrays
- arrays can only contain data of the same data type (similar to atomic vectors)

## Array creation
- direct creation with `np.array([])`

In [16]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
a = np.array([1, 2, 3])
print(a) # printing an array appears different from the array([]) in ipython

[1 2 3]


In [12]:
b = np.array([1, 2, 3.0])
print(b) # the 3.0 is a float and will coerce other values to floats

[1. 2. 3.]


In [23]:
c = np.array([1, 2, "3"]) # coerced to strings
print(c)

['1' '2' '3']
