In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn import linear_model

In [3]:
from sklearn.datasets import load_boston
boston = load_boston()

In [5]:
# we will convert to pandas dataframe
bos = pd.DataFrame(boston.data)
bos.columns = boston.feature_names
bos.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [10]:
bosmodel = linear_model.LinearRegression() # create an instance of the linear regression model

In [9]:
boston.target.shape  # the 1 dimensional array of values that we are trying to predict

(506,)

In [12]:
X = bos

In [13]:
bosmodel.fit(X, boston.target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
bosmodel.coef_

array([-1.07170557e-01,  4.63952195e-02,  2.08602395e-02,  2.68856140e+00,
       -1.77957587e+01,  3.80475246e+00,  7.51061703e-04, -1.47575880e+00,
        3.05655038e-01, -1.23293463e-02, -9.53463555e-01,  9.39251272e-03,
       -5.25466633e-01])

In [19]:
# r squared value
bosmodel.score(X, boston.target)  # when we fit all of the data points

0.7406077428649428

In [16]:
ridgemodel = linear_model.Ridge(alpha = 1, normalize = True)  # normalize will put the values on similar scales
ridgemodel.fit(X, boston.target)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=True,
   random_state=None, solver='auto', tol=0.001)

In [17]:
ridgemodel.coef_

array([-5.93676290e-02,  1.77024601e-02, -7.24047166e-02,  2.31154826e+00,
       -3.92764313e+00,  2.87459101e+00, -9.29694103e-03, -2.49665149e-01,
       -4.52010290e-03, -2.73587810e-03, -5.35677921e-01,  6.21794574e-03,
       -2.61501409e-01])

In [20]:
ridgemodel.score(X, boston.target)

0.6350140721217934

In [23]:
from sklearn.model_selection import cross_val_score

ridgemodel = linear_model.Ridge(alpha = 1, normalize = True)

cv_results = cross_val_score(ridgemodel, X, boston.target, cv = 5)  # 5 fold cross validation

print(cv_results)  

[0.57403125 0.62857757 0.34433611 0.26156525 0.32160065]


In [24]:
from sklearn.model_selection import cross_val_score

bosmodel = linear_model.LinearRegression()

cv_results = cross_val_score(bosmodel, X, boston.target, cv = 5)  # 5 fold cross validation

print(cv_results)  # lots of variation
# an undesirable trait

[ 0.63861069  0.71334432  0.58645134  0.07842495 -0.26312455]
